const fs = require("fs");
const { v4: uuidv4 } = require("uuid");

const filename = "data.json";

const names = [
  "Hugo",
  "Martín",
  "Lucas",
  "Mateo",
  "Leo",
  "Daniel",
  "Alejandro",
  "Pablo",
  "Manuel",
  "Álvaro",
  "Adrián",
  "David",
  "Mario",
  "Enzo",
  "Diego",
  "Marcos",
  "Izan",
  "Javier",
  "Marco",
  "Álex",
  "Bruno",
  "Oliver",
  "Miguel",
  "Thiago",
  "Antonio",
  "Marc",
  "Carlos",
  "Ángel",
  "Juan",
  "Gonzalo",
  "Gael",
  "Sergio",
  "Nicolás",
  "Dylan",
  "Gabriel",
  "Jorge",
  "José",
  "Adam",
  "Liam",
  "Eric",
  "Samuel",
  "Darío",
  "Héctor",
  "Luca",
  "Iker",
  "Amir",
  "Rodrigo",
  "Saúl",
  "Víctor",
  "Francisco",
  "Iván",
  "Jesús",
  "Jaime",
  "Aarón",
  "Rubén",
  "Ian",
  "Guillermo",
  "Erik",
  "Mohamed",
  "Julen",
  "Luis",
  "Pau",
  "Unai",
  "Rafael",
  "Joel",
  "Alberto",
  "Pedro",
  "Raúl",
  "Aitor",
  "Santiago",
  "Rayan",
  "Pol",
  "Nil",
  "Noah",
  "Jan",
  "Asier",
  "Fernando",
  "Alonso",
  "Matías",
  "Biel",
  "Andrés",
  "Axel",
  "Ismael",
  "Martí",
  "Arnau",
  "Imran",
  "Luka",
  "Ignacio",
  "Aleix",
  "Alan",
  "Elías",
  "Omar",
  "Isaac",
  "Youssef",
  "Jon",
  "Teo",
  "Mauro",
  "Óscar",
  "Cristian",
  "Leonardo",
];

const cities = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Miami",
  "London",
  "Paris",
  "Berlin",
  "Tokyo",
  "Beijing",
  "Sydney",
  "Melbourne",
  "Toronto",
  "Vancouver",
  "Mexico City",
  "São Paulo",
  "Buenos Aires",
  "Rio de Janeiro",
  "Santiago",
  "Lima",
  "Madrid",
  "Barcelona",
  "Rome",
  "Milan",
  "Moscow",
  "Saint Petersburg",
  "Istanbul",
  "Athens",
  "Cairo",
  "Johannesburg",
  "Nairobi",
  "Lagos",
  "Casablanca",
  "Bangkok",
  "Manila",
  "Jakarta",
  "Kuala Lumpur",
  "Singapore",
  "Seoul",
  "Hong Kong",
  "Shanghai",
  "Dubai",
  "Abu Dhabi",
  "Doha",
  "Riyadh",
  "Tel Aviv",
  "Jerusalem",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Chennai",
  "Kolkata",
  "Karachi",
  "Lahore",
  "Dhaka",
  "Kathmandu",
  "Colombo",
  "Tehran",
  "Baghdad",
  "Kabul",
  "Islamabad",
  "Damascus",
  "Beirut",
  "Amman",
  "Tunis",
  "Algiers",
  "Rabat",
  "Addis Ababa",
  "Accra",
  "Dakar",
  "Kampala",
  "Harare",
  "Lusaka",
  "Maputo",
  "Pretoria",
  "Cape Town",
  "Brisbane",
  "Auckland",
  "Wellington",
  "Lima",
  "La Paz",
  "Quito",
  "Caracas",
  "Bogota",
  "Montevideo",
  "Asuncion",
  "San Salvador",
  "Guatemala City",
  "Tegucigalpa",
  "Managua",
  "Panama City",
  "San Jose",
  "Kingston",
  "Port-au-Prince",
  "Santo Domingo",
  "Havana",
  "Reykjavik",
  "Oslo",
  "Stockholm",
  "Copenhagen",
];

const stream = fs.createWriteStream(filename);

let max = 1000000;

stream.write("[");

for (let i = 0; i < max; i++) {
  const name = names[rand(0, 99)];
  const content = {
    id: uuidv4(),
    name: name,
    email: name + rand(50, 100) + "@ascript.com",
    address: "Av " + name + " - " + rand(2, 100),
    phone: `+${rand(1000000000, 9999999999)}`,
    postal: `${rand(100000, 999999)}`,
    age: rand(18, 60),
    city: cities[rand(0, 99)],
  };
  if (i < max - 1) {
    appendFile(content);
  } else {
    closeFile(content);
    stream.end();
    stream.on("finish", () => {
      console.log(`Successfully wrote ${max} records to ${filename}`);
    });
  }
}

function appendFile(content) {
  stream.write(JSON.stringify(content) + ",\n");
}

function closeFile(content) {
  stream.write(JSON.stringify(content) + "]");
}

function rand(min, max) {
  return Math.floor(Math.random() * (max - min) + min);
}
